Repository Nexters/meme-wiki-iOS, pull requests merged in 2025-08, with the labels that each got.

#23 [Feature/#20] 검색 결과 View 구현
  Meme/Meme.xcodeproj/project.pbxproj
  Meme/Meme/Sources/DesignSystem/View/SearchInfoView.swift
  Meme/Meme/Sources/DesignSystem/View/SearchResultView.swift
  Meme/Meme/Sources/Wiki/Domain/Entity/MemeSearchItem.swift
Labels: feature

#30 [Feature/#13] 디자인시스템 - 아이콘
  Meme/Meme/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/AppIcon.appiconset/Symbol.png
  Meme/Meme/Resources/Assets.xcassets/Banner/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Banner/banner_custom_1.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Banner/banner_custom_1.imageset/banner_custom_1.svg
  Meme/Meme/Resources/Assets.xcassets/Banner/banner_custom_2.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Banner/banner_custom_2.imageset/banner_custom_2.svg
  Meme/Meme/Resources/Assets.xcassets/Banner/banner_custom_3.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Banner/banner_custom_3.imageset/banner_custom_3.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_arrow_left.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_arrow_left.imageset/icon_arrow_left.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_arrow_right.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_arrow_right.imageset/icon_arrow_right.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_arrow_top.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_arrow_top.imageset/icon_arrow_top.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_cheveron_left.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_cheveron_left.imageset/icon_cheveron_left.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_chevron_right.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_chevron_right.imageset/icon_chevron_right.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_download.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_download.imageset/icon_download.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_edit.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_edit.imageset/icon_edit.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_edit_plus.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_edit_plus.imageset/icon_edit_plus.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_home.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_home.imageset/icon_home.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_input_delete.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_input_delete.imageset/icon_input_delete.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_logo.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_logo.imageset/Logo.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_menu.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_menu.imageset/icon_menu.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_more_horizontal.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_more_horizontal.imageset/icon_more_horizontal.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_more_vertical.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_more_vertical.imageset/icon_more_vertical.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_redo.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_redo.imageset/icon_redo.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_search_20.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_search_20.imageset/icon_search_20.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_search_24.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_search_24.imageset/icon_search_24.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_share.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_share.imageset/icon_share.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_undo.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_undo.imageset/icon_undo.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_x.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_x.imageset/icon_x.svg
  Meme/Meme/Resources/Assets.xcassets/Image/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_blue.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_blue.imageset/symbol_blue.svg
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_default.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_default.imageset/symbol_default.svg
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_pink.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_pink.imageset/symbol_pink.svg
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_yellow.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Image/symbol_yellow.imageset/symbol_yellow.svg
Labels: setting, feature

#35 [Feature/#34] 카테고리 검색 화면 레이아웃 구현
  Meme/Meme.xcodeproj/project.pbxproj
  Meme/Meme/Sources/Wiki/Domain/Entity/CategoryItem.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/Model/MemeCategorySection.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/View/MemeSearchHeaderView.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/View/SearchCategoryCell.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/View/SeparatorDecorationView.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/ViewController/MemeCategoryViewController.swift
Labels: feature

#42 [Feature/#38] 카테고리 검색 화면 로직 구현
  Meme/Meme.xcodeproj/project.pbxproj
  Meme/Meme/Sources/Base/Web/WikiWebViewController.swift
  Meme/Meme/Sources/DesignSystem/Extensions/UIView++Extension.swift
  Meme/Meme/Sources/DesignSystem/View/SearchThumbnailView.swift
  Meme/Meme/Sources/SceneDelegate.swift
  Meme/Meme/Sources/Wiki/Data/DTO/LobbyResponse.swift
  Meme/Meme/Sources/Wiki/Data/DTO/SearchResponseDTO.swift
  Meme/Meme/Sources/Wiki/Data/Network/CategoryAPI.swift
  Meme/Meme/Sources/Wiki/Data/Repository/CategoryRepository.swift
  Meme/Meme/Sources/Wiki/Domain/Entity/Lobby.swift
  Meme/Meme/Sources/Wiki/Domain/Entity/MemeSearchItem.swift
  Meme/Meme/Sources/Wiki/Domain/Entity/Thumbnail.swift
  Meme/Meme/Sources/Wiki/Domain/Interface/Repository/CategoryRepositoryInterface.swift
  Meme/Meme/Sources/Wiki/Domain/Interface/UseCase/CategoryMemeUseCaseInterface.swift
  Meme/Meme/Sources/Wiki/Domain/UseCase/CategoryMemeUseCase.swift
  Meme/Meme/Sources/Wiki/Domain/UseCase/Lobby/CategoriesUseCase.swift
  Meme/Meme/Sources/Wiki/Domain/UseCase/Lobby/LobbyUseCase.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/View/MemeSearchHeaderView.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/View/SearchCategoryCell.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/ViewController/MemeCategoryViewController.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/ViewModel/CategoryViewModel.swift
  Meme/Meme/Sources/Wiki/Presentation/Main/View/MemeMainViewController.swift
Labels: feature

#46 [Feature/#44] 구현된 화면 연결
  Meme/Meme.xcodeproj/project.pbxproj
  Meme/Meme/Resources/Info.plist
  Meme/Meme/Sources/Wiki/Presentation/BaseViewController.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/ViewController/MemeCategoryViewController.swift
  Meme/Meme/Sources/Wiki/Presentation/Category/ViewModel/CategoryViewModel.swift
  Meme/Meme/Sources/Wiki/Presentation/Main/View/MemeMainViewController.swift
  Meme/Meme/Sources/Wiki/Presentation/Search/View/MemeSearchEmptyCell.swift
  Meme/Meme/Sources/Wiki/Presentation/Search/ViewController/MemeSearchViewController.swift
  Meme/Meme/Sources/Wiki/Presentation/UIViewController++Extension.swift
Labels: feature

#55 [Fix#50] 검색 결과 존재하는 경우에 검색 시 버그 수정
  Meme/Meme/Sources/Wiki/Presentation/Search/ViewController/MemeSearchViewController.swift
Labels: bug

#54 [Feature/#41] 밈꾸 텍스트 추가
  Meme/Meme.xcodeproj/project.pbxproj
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_delete.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_delete.imageset/icon_delete.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_more_circle.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_more_circle.imageset/icon_more_circle.svg
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_text.imageset/Contents.json
  Meme/Meme/Resources/Assets.xcassets/Icon/icon_text.imageset/icon_text.svg
  Meme/Meme/Sources/DesignSystem/View/TouchHandleView.swift
  Meme/Meme/Sources/Wiki/Presentation/Custom/View/EditToolView.swift
  Meme/Meme/Sources/Wiki/Presentation/Custom/View/MemeCustomViewController.swift
  Meme/Meme/Sources/Wiki/Presentation/Custom/View/TextEditView.swift
  Meme/Meme/Sources/Wiki/Presentation/Custom/View/TextStylePanelView.swift
  Meme/Meme/Sources/Wiki/Presentation/Custom/View/UserTextView.swift
Labels: feature
